package com.newtouch.structfund.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SaleBillDate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.REGISTER_CODE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private String registerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.FUND_CODE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private String fundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.DISTRIBUTOR_CODE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private String distributorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.DELAY_DATE_ALLOT
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Integer delayDateAllot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.DELAY_DATE_PURSE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Integer delayDatePurse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.DELAY_DATE_REDEEM
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Integer delayDateRedeem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.DELAY_DATE_BONUS
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Integer delayDateBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.DELAY_DATE_CHANGE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Integer delayDateChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.MONEY_TYPE_ALLOT
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private String moneyTypeAllot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.MIN_BONUS
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private BigDecimal minBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.DELAY_DATE_ADV_END
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Integer delayDateAdvEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.DELAY_DATE_END
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Integer delayDateEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.CONF_REDEEM_DAYS
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Integer confRedeemDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.TIMESTAMP_C
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Date timestampC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_billdate.TIMESTAMP_U
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    private Date timestampU;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.REGISTER_CODE
     *
     * @return the value of sale_billdate.REGISTER_CODE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public String getRegisterCode() {
        return registerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.REGISTER_CODE
     *
     * @param registerCode the value for sale_billdate.REGISTER_CODE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setRegisterCode(String registerCode) {
        this.registerCode = registerCode == null ? null : registerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.FUND_CODE
     *
     * @return the value of sale_billdate.FUND_CODE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.FUND_CODE
     *
     * @param fundCode the value for sale_billdate.FUND_CODE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.DISTRIBUTOR_CODE
     *
     * @return the value of sale_billdate.DISTRIBUTOR_CODE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public String getDistributorCode() {
        return distributorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.DISTRIBUTOR_CODE
     *
     * @param distributorCode the value for sale_billdate.DISTRIBUTOR_CODE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setDistributorCode(String distributorCode) {
        this.distributorCode = distributorCode == null ? null : distributorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.DELAY_DATE_ALLOT
     *
     * @return the value of sale_billdate.DELAY_DATE_ALLOT
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Integer getDelayDateAllot() {
        return delayDateAllot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.DELAY_DATE_ALLOT
     *
     * @param delayDateAllot the value for sale_billdate.DELAY_DATE_ALLOT
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setDelayDateAllot(Integer delayDateAllot) {
        this.delayDateAllot = delayDateAllot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.DELAY_DATE_PURSE
     *
     * @return the value of sale_billdate.DELAY_DATE_PURSE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Integer getDelayDatePurse() {
        return delayDatePurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.DELAY_DATE_PURSE
     *
     * @param delayDatePurse the value for sale_billdate.DELAY_DATE_PURSE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setDelayDatePurse(Integer delayDatePurse) {
        this.delayDatePurse = delayDatePurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.DELAY_DATE_REDEEM
     *
     * @return the value of sale_billdate.DELAY_DATE_REDEEM
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Integer getDelayDateRedeem() {
        return delayDateRedeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.DELAY_DATE_REDEEM
     *
     * @param delayDateRedeem the value for sale_billdate.DELAY_DATE_REDEEM
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setDelayDateRedeem(Integer delayDateRedeem) {
        this.delayDateRedeem = delayDateRedeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.DELAY_DATE_BONUS
     *
     * @return the value of sale_billdate.DELAY_DATE_BONUS
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Integer getDelayDateBonus() {
        return delayDateBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.DELAY_DATE_BONUS
     *
     * @param delayDateBonus the value for sale_billdate.DELAY_DATE_BONUS
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setDelayDateBonus(Integer delayDateBonus) {
        this.delayDateBonus = delayDateBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.DELAY_DATE_CHANGE
     *
     * @return the value of sale_billdate.DELAY_DATE_CHANGE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Integer getDelayDateChange() {
        return delayDateChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.DELAY_DATE_CHANGE
     *
     * @param delayDateChange the value for sale_billdate.DELAY_DATE_CHANGE
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setDelayDateChange(Integer delayDateChange) {
        this.delayDateChange = delayDateChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.MONEY_TYPE_ALLOT
     *
     * @return the value of sale_billdate.MONEY_TYPE_ALLOT
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public String getMoneyTypeAllot() {
        return moneyTypeAllot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.MONEY_TYPE_ALLOT
     *
     * @param moneyTypeAllot the value for sale_billdate.MONEY_TYPE_ALLOT
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setMoneyTypeAllot(String moneyTypeAllot) {
        this.moneyTypeAllot = moneyTypeAllot == null ? null : moneyTypeAllot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.MIN_BONUS
     *
     * @return the value of sale_billdate.MIN_BONUS
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public BigDecimal getMinBonus() {
        return minBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.MIN_BONUS
     *
     * @param minBonus the value for sale_billdate.MIN_BONUS
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setMinBonus(BigDecimal minBonus) {
        this.minBonus = minBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.DELAY_DATE_ADV_END
     *
     * @return the value of sale_billdate.DELAY_DATE_ADV_END
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Integer getDelayDateAdvEnd() {
        return delayDateAdvEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.DELAY_DATE_ADV_END
     *
     * @param delayDateAdvEnd the value for sale_billdate.DELAY_DATE_ADV_END
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setDelayDateAdvEnd(Integer delayDateAdvEnd) {
        this.delayDateAdvEnd = delayDateAdvEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.DELAY_DATE_END
     *
     * @return the value of sale_billdate.DELAY_DATE_END
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Integer getDelayDateEnd() {
        return delayDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.DELAY_DATE_END
     *
     * @param delayDateEnd the value for sale_billdate.DELAY_DATE_END
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setDelayDateEnd(Integer delayDateEnd) {
        this.delayDateEnd = delayDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.CONF_REDEEM_DAYS
     *
     * @return the value of sale_billdate.CONF_REDEEM_DAYS
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Integer getConfRedeemDays() {
        return confRedeemDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.CONF_REDEEM_DAYS
     *
     * @param confRedeemDays the value for sale_billdate.CONF_REDEEM_DAYS
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setConfRedeemDays(Integer confRedeemDays) {
        this.confRedeemDays = confRedeemDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.TIMESTAMP_C
     *
     * @return the value of sale_billdate.TIMESTAMP_C
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Date getTimestampC() {
        return timestampC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.TIMESTAMP_C
     *
     * @param timestampC the value for sale_billdate.TIMESTAMP_C
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setTimestampC(Date timestampC) {
        this.timestampC = timestampC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_billdate.TIMESTAMP_U
     *
     * @return the value of sale_billdate.TIMESTAMP_U
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public Date getTimestampU() {
        return timestampU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_billdate.TIMESTAMP_U
     *
     * @param timestampU the value for sale_billdate.TIMESTAMP_U
     *
     * @mbggenerated Tue Mar 17 01:59:38 CST 2020
     */
    public void setTimestampU(Date timestampU) {
        this.timestampU = timestampU;
    }

    @Override
    public String toString() {
        return "SaleBillDate{" +
                "registerCode='" + registerCode + '\'' +
                ", fundCode='" + fundCode + '\'' +
                ", distributorCode='" + distributorCode + '\'' +
                ", delayDateAllot=" + delayDateAllot +
                ", delayDatePurse=" + delayDatePurse +
                ", delayDateRedeem=" + delayDateRedeem +
                ", delayDateBonus=" + delayDateBonus +
                ", delayDateChange=" + delayDateChange +
                ", moneyTypeAllot='" + moneyTypeAllot + '\'' +
                ", minBonus=" + minBonus +
                ", delayDateAdvEnd=" + delayDateAdvEnd +
                ", delayDateEnd=" + delayDateEnd +
                ", confRedeemDays=" + confRedeemDays +
                ", timestampC=" + timestampC +
                ", timestampU=" + timestampU +
                '}';
    }
}